spring:
  application:
    name: spring-admin
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '系统管理'
      paths-to-match: '/**'
      packages-to-scan:
        - com.chuxin.springadmin.controller
        - com.chuxin.springadmin.modules.auth.controller

knife4j:
  enable: true
  setting:
    language: zh_cn